### ISSUE TITLE
Präsentation

### ISSUE THREAD

**Issue by hannahsophiegr** [ID-Start-Winter22/chat-team-6#19]
Wer möchte die denn machen? @lauradax wärst du wieder bereit eine zu machen, oder soll sie sonst jemand anderes machen?

**Comment by hannahsophiegr** [comment]
Wir brauchen gar keine Präsentation oder?

**Comment by lauradax** [comment]
grundsätzlich kann ich das schon machen, in Moodle steht allerdings, dass wir lediglich eine Demo des bots vorführen sollen, also keine keynote
