### ISSUE TITLE
Ausflugsziele

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/chat-team-6#9]
Woher wollen wir diese nehmen? Auf welchen Rahmen wollen wir uns beschränken?

**Comment by hannahsophiegr** [comment]
ich hab jetzt für die drinnen Aktivitäten den Natur Punkt weg gemacht. Außerdem hab ich aus <1h und 1-2h eins gemacht mit <2h. Bei den draußen Aktivitäten hab ich alles was etwas kostet zusammengefasst, da war es irgendwie sonst echt schwer noch sachen zu finden. Es steht jetzt bei jedem zumindest mal eine Sache da. Wir können schauen, des wir es im laufe der Zeit noch erweitern, wenn uns was einfällt, aber ich denke das sollte jetzt so erstmal passen

**Comment by hannahsophiegr** [comment]
Ich würde sie noch so aufbereiten, dass wir alle Infos für das Dialogfeld bereit haben
